<?php

use Illuminate\Database\Seeder;

class UsersTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('users')->insert([
        
        [
        'name' => 'Eiei',
        'hometeam' => '1-A',
        'codingteam' => 'Letian panda',
        'password' => bcrypt('100014097'),
        ],
        [
        'name' => 'Kosuke2',
        'hometeam' => '1-A',
        'codingteam' => 'TK Kingdom',
        'password' => bcrypt('100013914'),
        ],
        [
        'name' => 'Lucia',
        'hometeam' => '1-A',
        'codingteam' => 'Fortune',
        'password' => bcrypt('100013900'),
        ],
        [
        'name' => 'Mio',
        'hometeam' => '1-A',
        'codingteam' => 'Jasmine',
        'password' => bcrypt('100013867'),
        ],
        [
        'name' => 'Moo',
        'hometeam' => '1-A',
        'codingteam' => 'A BANANA',
        'password' => bcrypt('100013871'),
        ],
        [
        'name' => 'Tkay',
        'hometeam' => '1-A',
        'codingteam' => '新鮮グミ',
        'password' => bcrypt('100014041'),
        ],
        [
        'name' => 'Chee',
        'hometeam' => '1-B',
        'codingteam' => 'TERAKOYA',
        'password' => bcrypt('100013978'),
        ],
        [
        'name' => 'Hiromi',
        'hometeam' => '1-B',
        'codingteam' => 'Pocket 6',
        'password' => bcrypt('100013870'),
        ],
        [
        'name' => 'Hono',
        'hometeam' => '1-B',
        'codingteam' => '新鮮グミ',
        'password' => bcrypt('100013868'),
        ],
        [
        'name' => 'Taisei',
        'hometeam' => '1-B',
        'codingteam' => 'JETS',
        'password' => bcrypt('100014063'),
        ],
        [
        'name' => 'Taito',
        'hometeam' => '1-B',
        'codingteam' => 'SAKEty (酒ティー)',
        'password' => bcrypt('100013932'),
        ],
        [
        'name' => 'Yuki1',
        'hometeam' => '1-B',
        'codingteam' => 'JETS',
        'password' => bcrypt('100013920'),
        ],
        [
        'name' => 'Amy',
        'hometeam' => '1-C',
        'codingteam' => 'SAKEty (酒ティー)',
        'password' => bcrypt('100014131'),
        ],
        [
        'name' => 'Hiro3',
        'hometeam' => '1-C',
        'codingteam' => 'チームきりんさん',
        'password' => bcrypt('100014133'),
        ],
        [
        'name' => 'Jet',
        'hometeam' => '1-C',
        'codingteam' => 'JETS',
        'password' => bcrypt('100013897'),
        ],
        [
        'name' => 'Judy',
        'hometeam' => '1-C',
        'codingteam' => 'チームきりんさん',
        'password' => bcrypt('100014044'),
        ],
        [
        'name' => 'Ryo1',
        'hometeam' => '1-C',
        'codingteam' => 'Pocket 6',
        'password' => bcrypt('100013926'),
        ],
        [
        'name' => 'Ryo3',
        'hometeam' => '1-C',
        'codingteam' => 'ぽなるけみり',
        'password' => bcrypt('100014268'),
        ],
        [
        'name' => 'Yukie',
        'hometeam' => '1-C',
        'codingteam' => 'Kiwami Pudding',
        'password' => bcrypt('100014134'),
        ],
        [
        'name' => 'Hayato',
        'hometeam' => '2-A',
        'codingteam' => 'TERAKOYA',
        'password' => bcrypt('100013869'),
        ],
        [
        'name' => 'Kurumi',
        'hometeam' => '2-A',
        'codingteam' => 'Avengers',
        'password' => bcrypt('100014001'),
        ],
        [
        'name' => 'Onoshin',
        'hometeam' => '2-A',
        'codingteam' => 'チームきりんさん',
        'password' => bcrypt('119000253'),
        ],
        [
        'name' => 'Shingo',
        'hometeam' => '2-A',
        'codingteam' => 'Koders',
        'password' => bcrypt('100013917'),
        ],
        [
        'name' => 'Toko',
        'hometeam' => '2-A',
        'codingteam' => 'TK Kingdom',
        'password' => bcrypt('100013946'),
        ],
        [
        'name' => 'Lisa',
        'hometeam' => '2-A',
        'codingteam' => 'Noisyy',
        'password' => bcrypt('100014092'),
        ],
        [
        'name' => 'Jeri',
        'hometeam' => '2-B',
        'codingteam' => 'Avengers',
        'password' => bcrypt('100014128'),
        ],
        [
        'name' => 'Mia2',
        'hometeam' => '2-B',
        'codingteam' => 'Letian panda',
        'password' => bcrypt('100013874'),
        ],
        [
        'name' => 'Mizu',
        'hometeam' => '2-B',
        'codingteam' => 'Noisyy',
        'password' => bcrypt('100014086'),
        ],
        [
        'name' => 'Rei',
        'hometeam' => '2-B',
        'codingteam' => 'A BANANA',
        'password' => bcrypt('100013937'),
        ],
        [
        'name' => 'Toru',
        'hometeam' => '2-B',
        'codingteam' => '新鮮グミ',
        'password' => bcrypt('100014066'),
        ],
        [
        'name' => 'Aya',
        'hometeam' => '2-C',
        'codingteam' => 'kara-age',
        'password' => bcrypt('100014119'),
        ],
        [
        'name' => 'Kitty',
        'hometeam' => '2-C',
        'codingteam' => 'TK Kingdom',
        'password' => bcrypt('100013940'),
        ],
        [
        'name' => 'Kiyo',
        'hometeam' => '2-C',
        'codingteam' => 'Noisyy',
        'password' => bcrypt('100013938'),
        ],
        [
        'name' => 'Koki',
        'hometeam' => '2-C',
        'codingteam' => 'ぽなるけみり',
        'password' => bcrypt('100013934'),
        ],
        [
        'name' => 'Rumi',
        'hometeam' => '2-C',
        'codingteam' => 'CodeWars',
        'password' => bcrypt('100013999'),
        ],
        [
        'name' => 'Ryo2',
        'hometeam' => '2-C',
        'codingteam' => 'チームきりんさん',
        'password' => bcrypt('100014130'),
        ],
        [
        'name' => 'Sumi',
        'hometeam' => '2-C',
        'codingteam' => 'SAKEty (酒ティー)',
        'password' => bcrypt('100014123'),
        ],
        [
        'name' => 'Yuya',
        'hometeam' => '3-A',
        'codingteam' => 'TWICE',
        'password' => bcrypt('100013866'),
        ],
        [
        'name' => 'Mako',
        'hometeam' => '3-A',
        'codingteam' => 'Siésta',
        'password' => bcrypt('100013951'),
        ],
        [
        'name' => 'Nitch',
        'hometeam' => '3-A',
        'codingteam' => 'Pandanity',
        'password' => bcrypt('100013948'),
        ],
        [
        'name' => 'Lou',
        'hometeam' => '3-A',
        'codingteam' => 'The U.K',
        'password' => bcrypt('100013944'),
        ],
        [
        'name' => 'Mizuki1',
        'hometeam' => '3-A',
        'codingteam' => 'Daichi+no+Megumi',
        'password' => bcrypt('100014031'),
        ],
        [
        'name' => 'Momo1',
        'hometeam' => '3-A',
        'codingteam' => 'いいとも',
        'password' => bcrypt('100013992'),
        ],
        [
        'name' => 'Shiho',
        'hometeam' => '3-B',
        'codingteam' => 'Mkpali(ムカパリ)',
        'password' => bcrypt('100014122'),
        ],
        [
        'name' => 'Sho',
        'hometeam' => '3-B',
        'codingteam' => 'Pandanity',
        'password' => bcrypt('100013979'),
        ],
        [
        'name' => 'Touchy',
        'hometeam' => '3-B',
        'codingteam' => 'Daichi+no+Megumi',
        'password' => bcrypt('100014067'),
        ],
        [
        'name' => 'Raki',
        'hometeam' => '3-B',
        'codingteam' => 'The U.K',
        'password' => bcrypt('100013968'),
        ],
        [
        'name' => 'Yui2',
        'hometeam' => '3-B',
        'codingteam' => 'Kolkata (カルカッタ)',
        'password' => bcrypt('100014043'),
        ],
        [
        'name' => 'July',
        'hometeam' => '3-B',
        'codingteam' => 'Porsche',
        'password' => bcrypt('100014120'),
        ],
        [
        'name' => 'Issei',
        'hometeam' => '3-C',
        'codingteam' => 'チームきりんさん',
        'password' => bcrypt('100014000'),
        ],
        [
        'name' => 'Kana2',
        'hometeam' => '3-C',
        'codingteam' => 'ぽなるけみり',
        'password' => bcrypt('100013881'),
        ],
        [
        'name' => 'Kota',
        'hometeam' => '3-C',
        'codingteam' => 'なだ万',
        'password' => bcrypt('100013952'),
        ],
        [
        'name' => 'Nana4',
        'hometeam' => '3-C',
        'codingteam' => 'ぽなるけみり',
        'password' => bcrypt('100014052'),
        ],
        [
        'name' => 'Jun2',
        'hometeam' => '3-C',
        'codingteam' => 'Team Sekaikan',
        'password' => bcrypt('100013894'),
        ],
        [
        'name' => 'Manatee',
        'hometeam' => '3-C',
        'codingteam' => 'Team Sekaikan',
        'password' => bcrypt('100013880'),
        ],
        [
        'name' => 'Taiki',
        'hometeam' => '3-C',
        'codingteam' => 'kemkow',
        'password' => bcrypt('100014038'),
        ],
        [
        'name' => 'Nana1',
        'hometeam' => '4-A',
        'codingteam' => 'Daichi+no+Megumi',
        'password' => bcrypt('100013909'),
        ],
        [
        'name' => 'Tomo1',
        'hometeam' => '4-A',
        'codingteam' => 'Team Kay ',
        'password' => bcrypt('100013954'),
        ],
        [
        'name' => 'Yookie',
        'hometeam' => '4-A',
        'codingteam' => 'BoB',
        'password' => bcrypt('100014069'),
        ],
        [
        'name' => 'Kotoko',
        'hometeam' => '4-A',
        'codingteam' => 'TWICE',
        'password' => bcrypt('100013913'),
        ],
        [
        'name' => 'Kaho',
        'hometeam' => '4-A',
        'codingteam' => 'The U.K',
        'password' => bcrypt('100013987'),
        ],
        [
        'name' => 'Eriko',
        'hometeam' => '4-B',
        'codingteam' => 'JETS',
        'password' => bcrypt('100014040'),
        ],
        [
        'name' => 'Morizo',
        'hometeam' => '4-B',
        'codingteam' => 'Team One',
        'password' => bcrypt('100013936'),
        ],
        [
        'name' => 'Ray',
        'hometeam' => '4-B',
        'codingteam' => 'Pocket 6',
        'password' => bcrypt('100013949'),
        ],
        [
        'name' => 'Yo',
        'hometeam' => '4-B',
        'codingteam' => 'Jasmine',
        'password' => bcrypt('100013967'),
        ],
        [
        'name' => 'Yui1',
        'hometeam' => '4-B',
        'codingteam' => 'BoB',
        'password' => bcrypt('100013973'),
        ],
        [
        'name' => 'Ryohei',
        'hometeam' => '4-B',
        'codingteam' => 'The U.K',
        'password' => bcrypt('100013889'),
        ],
        [
        'name' => 'Ikuma',
        'hometeam' => '4-C',
        'codingteam' => 'Amigos',
        'password' => bcrypt('100013969'),
        ],
        [
        'name' => 'Jamie',
        'hometeam' => '4-C',
        'codingteam' => 'ひよこさん組',
        'password' => bcrypt('100014039'),
        ],
        [
        'name' => 'Ryotaro',
        'hometeam' => '4-C',
        'codingteam' => 'ひよこさん組',
        'password' => bcrypt('100014007'),
        ],
        [
        'name' => 'Tsugumi',
        'hometeam' => '4-C',
        'codingteam' => 'Noisyy',
        'password' => bcrypt('100013898'),
        ],
        [
        'name' => 'Sara',
        'hometeam' => '4-C',
        'codingteam' => 'TWICE',
        'password' => bcrypt('100013906'),
        ],
        [
        'name' => 'Taiga',
        'hometeam' => '4-C',
        'codingteam' => 'Amigos',
        'password' => bcrypt('100014071'),
        ],
        [
        'name' => 'Ally',
        'hometeam' => '5-A',
        'codingteam' => '新鮮グミ',
        'password' => bcrypt('100013872'),
        ],
        [
        'name' => 'Jumpei',
        'hometeam' => '5-A',
        'codingteam' => 'YAKITOMATO',
        'password' => bcrypt('100013980'),
        ],
        [
        'name' => 'Ayu',
        'hometeam' => '5-A',
        'codingteam' => 'Team Kay ',
        'password' => bcrypt('100013939'),
        ],
        [
        'name' => 'Kazu',
        'hometeam' => '5-A',
        'codingteam' => 'Kolkata (カルカッタ)',
        'password' => bcrypt('100013972'),
        ],
        [
        'name' => 'Koh',
        'hometeam' => '5-A',
        'codingteam' => 'Letian panda',
        'password' => bcrypt('100013910'),
        ],
        [
        'name' => 'Yana',
        'hometeam' => '5-A',
        'codingteam' => 'JIAOZI',
        'password' => bcrypt('100014117'),
        ],
        [
        'name' => 'Bolin',
        'hometeam' => '5-B',
        'codingteam' => 'Avengers',
        'password' => bcrypt('131000260'),
        ],
        [
        'name' => 'Colette',
        'hometeam' => '5-B',
        'codingteam' => 'Ra Ra Ra RIZAP',
        'password' => bcrypt('100013918'),
        ],
        [
        'name' => 'Karen',
        'hometeam' => '5-B',
        'codingteam' => 'JIAOZI',
        'password' => bcrypt('100013981'),
        ],
        [
        'name' => 'Mia1',
        'hometeam' => '5-B',
        'codingteam' => 'JIAOZI',
        'password' => bcrypt('100013990'),
        ],
        [
        'name' => 'Momo2',
        'hometeam' => '5-B',
        'codingteam' => '卍Olive卍',
        'password' => bcrypt('100013961'),
        ],
        [
        'name' => 'Kosuke1',
        'hometeam' => '5-B',
        'codingteam' => 'TK Kingdom',
        'password' => bcrypt('100013983'),
        ],
        [
        'name' => 'Jun3',
        'hometeam' => '5-C',
        'codingteam' => 'CodeWars',
        'password' => bcrypt('100013877'),
        ],
        [
        'name' => 'Mayu',
        'hometeam' => '5-C',
        'codingteam' => '卍Olive卍',
        'password' => bcrypt('100014002'),
        ],
        [
        'name' => 'Noffy',
        'hometeam' => '5-C',
        'codingteam' => 'Team Kay ',
        'password' => bcrypt('100013942'),
        ],
        [
        'name' => 'Taka1',
        'hometeam' => '5-C',
        'codingteam' => '御富士も梅雨',
        'password' => bcrypt('100014068'),
        ],
        [
        'name' => 'Yooda',
        'hometeam' => '5-C',
        'codingteam' => 'Kolkata (カルカッタ)',
        'password' => bcrypt('100013996'),
        ],
        [
        'name' => 'Ichi',
        'hometeam' => '5-C',
        'codingteam' => 'Letian panda',
        'password' => bcrypt('100014076'),
        ],
        [
        'name' => 'Zima',
        'hometeam' => '6-A',
        'codingteam' => 'TERAKOYA',
        'password' => bcrypt('100014099'),
        ],
        [
        'name' => 'Haluna',
        'hometeam' => '6-A',
        'codingteam' => 'いいとも',
        'password' => bcrypt('100013960'),
        ],
        [
        'name' => 'Kosei',
        'hometeam' => '6-A',
        'codingteam' => 'TWICE',
        'password' => bcrypt('100013924'),
        ],
        [
        'name' => 'Saaya',
        'hometeam' => '6-A',
        'codingteam' => 'Team Sekaikan',
        'password' => bcrypt('100014035'),
        ],
        [
        'name' => 'Habibi',
        'hometeam' => '6-A',
        'codingteam' => 'Kolkata (カルカッタ)',
        'password' => bcrypt('100014064'),
        ],
        [
        'name' => 'Shiki',
        'hometeam' => '6-A',
        'codingteam' => 'kara-age',
        'password' => bcrypt('100013985'),
        ],
        [
        'name' => 'Kanna1',
        'hometeam' => '6-B',
        'codingteam' => 'Koders',
        'password' => bcrypt('100014083'),
        ],
        [
        'name' => 'Nana3',
        'hometeam' => '6-B',
        'codingteam' => 'JETS',
        'password' => bcrypt('100014114'),
        ],
        [
        'name' => 'Tamo',
        'hometeam' => '6-B',
        'codingteam' => 'いいとも',
        'password' => bcrypt('100014088'),
        ],
        [
        'name' => 'Saki1',
        'hometeam' => '6-B',
        'codingteam' => 'いいとも',
        'password' => bcrypt('100014065'),
        ],
        [
        'name' => 'Soshi',
        'hometeam' => '6-B',
        'codingteam' => 'Y. Nature',
        'password' => bcrypt('100014129'),
        ],
        [
        'name' => 'Taka3',
        'hometeam' => '6-B',
        'codingteam' => 'Ra Ra Ra RIZAP',
        'password' => bcrypt('100013923'),
        ],
        [
        'name' => 'Ryoichi',
        'hometeam' => '6-C',
        'codingteam' => 'Jasmine',
        'password' => bcrypt('100013991'),
        ],
        [
        'name' => 'Rina',
        'hometeam' => '6-C',
        'codingteam' => 'BoB',
        'password' => bcrypt('100014085'),
        ],
        [
        'name' => 'Asuka',
        'hometeam' => '6-C',
        'codingteam' => 'SAKEty (酒ティー)',
        'password' => bcrypt('100013875'),
        ],
        [
        'name' => 'Mam',
        'hometeam' => '6-C',
        'codingteam' => 'ぽなるけみり',
        'password' => bcrypt('100013928'),
        ],
        [
        'name' => 'Minami1',
        'hometeam' => '6-C',
        'codingteam' => '御富士も梅雨',
        'password' => bcrypt('100013995'),
        ],
        [
        'name' => 'Minami2',
        'hometeam' => '7-A',
        'codingteam' => 'Ra Ra Ra RIZAP',
        'password' => bcrypt('100013993'),
        ],
        [
        'name' => 'Yuko',
        'hometeam' => '7-A',
        'codingteam' => 'Siésta',
        'password' => bcrypt('100014049'),
        ],
        [
        'name' => 'Paulo',
        'hometeam' => '7-A',
        'codingteam' => 'CodeWars',
        'password' => bcrypt('100014012'),
        ],
        [
        'name' => 'Daichi',
        'hometeam' => '7-A',
        'codingteam' => 'ひよこさん組',
        'password' => bcrypt('100014011'),
        ],
        [
        'name' => 'Maru',
        'hometeam' => '7-A',
        'codingteam' => 'BoB',
        'password' => bcrypt('100013935'),
        ],
        [
        'name' => 'Taka2',
        'hometeam' => '7-A',
        'codingteam' => '新鮮グミ',
        'password' => bcrypt('100014079'),
        ],
        [
        'name' => 'Karly',
        'hometeam' => '7-B',
        'codingteam' => 'ひよこさん組',
        'password' => bcrypt('100013950'),
        ],
        [
        'name' => 'Toy',
        'hometeam' => '7-B',
        'codingteam' => 'Team Kay ',
        'password' => bcrypt('100013873'),
        ],
        [
        'name' => 'Yossy',
        'hometeam' => '7-B',
        'codingteam' => 'Porsche',
        'password' => bcrypt('100014017'),
        ],
        [
        'name' => 'Nompi',
        'hometeam' => '7-B',
        'codingteam' => 'Team One',
        'password' => bcrypt('100014036'),
        ],
        [
        'name' => 'Poppo',
        'hometeam' => '7-B',
        'codingteam' => 'TWICE',
        'password' => bcrypt('119000255'),
        ],
        [
        'name' => 'So',
        'hometeam' => '7-B',
        'codingteam' => 'Medium Rare',
        'password' => bcrypt('100014113'),
        ],
        [
        'name' => 'Dai',
        'hometeam' => '7-C',
        'codingteam' => '御富士も梅雨',
        'password' => bcrypt('100014018'),
        ],
        [
        'name' => 'Hayley',
        'hometeam' => '7-C',
        'codingteam' => 'ひよこさん組',
        'password' => bcrypt('100014102'),
        ],
        [
        'name' => 'Sue',
        'hometeam' => '7-C',
        'codingteam' => 'チームきりんさん',
        'password' => bcrypt('100014048'),
        ],
        [
        'name' => 'Shoko',
        'hometeam' => '7-C',
        'codingteam' => 'CodeWars',
        'password' => bcrypt('100014006'),
        ],
        [
        'name' => 'Yoshi',
        'hometeam' => '7-C',
        'codingteam' => 'TWICE',
        'password' => bcrypt('100014019'),
        ],
        [
        'name' => 'Riku1',
        'hometeam' => '7-C',
        'codingteam' => 'Mkpali(ムカパリ)',
        'password' => bcrypt('100014084'),
        ],
        [
        'name' => 'Elie',
        'hometeam' => '8-A',
        'codingteam' => 'SAKEty (酒ティー)',
        'password' => bcrypt('100013929'),
        ],
        [
        'name' => 'Momona',
        'hometeam' => '8-A',
        'codingteam' => 'Kiwami Pudding',
        'password' => bcrypt('100013902'),
        ],
        [
        'name' => 'Saya',
        'hometeam' => '8-A',
        'codingteam' => 'なだ万',
        'password' => bcrypt('100013882'),
        ],
        [
        'name' => 'Beth',
        'hometeam' => '8-A',
        'codingteam' => 'Team Sekaikan',
        'password' => bcrypt('100014045'),
        ],
        [
        'name' => 'Koty',
        'hometeam' => '8-A',
        'codingteam' => 'Y. Nature',
        'password' => bcrypt('100014026'),
        ],
        [
        'name' => 'Yuto',
        'hometeam' => '8-A',
        'codingteam' => 'なだ万',
        'password' => bcrypt('100014024'),
        ],
        [
        'name' => 'Aki3',
        'hometeam' => '8-B',
        'codingteam' => 'Eternal Dragon',
        'password' => bcrypt('100014032'),
        ],
        [
        'name' => 'Coke',
        'hometeam' => '8-B',
        'codingteam' => 'Daichi+no+Megumi',
        'password' => bcrypt('100013930'),
        ],
        [
        'name' => 'Joy',
        'hometeam' => '8-B',
        'codingteam' => 'Team Kay ',
        'password' => bcrypt('100014030'),
        ],
        [
        'name' => 'Siena',
        'hometeam' => '8-B',
        'codingteam' => 'Kolkata (カルカッタ)',
        'password' => bcrypt('100013879'),
        ],
        [
        'name' => 'Kanna2',
        'hometeam' => '8-B',
        'codingteam' => 'Ra Ra Ra RIZAP',
        'password' => bcrypt('100013941'),
        ],
        [
        'name' => 'Amanda',
        'hometeam' => '8-C',
        'codingteam' => 'YAKITOMATO',
        'password' => bcrypt('100013884'),
        ],
        [
        'name' => 'Ikkun',
        'hometeam' => '8-C',
        'codingteam' => 'Team One',
        'password' => bcrypt('100013956'),
        ],
        [
        'name' => 'Ronald',
        'hometeam' => '8-C',
        'codingteam' => 'A BANANA',
        'password' => bcrypt('100014037'),
        ],
        [
        'name' => 'Gaku',
        'hometeam' => '8-C',
        'codingteam' => 'Siésta',
        'password' => bcrypt('100013912'),
        ],
        [
        'name' => 'Minako',
        'hometeam' => '8-C',
        'codingteam' => 'Pocket 6',
        'password' => bcrypt('100014020'),
        ],
        [
        'name' => 'Natsu2',
        'hometeam' => '8-C',
        'codingteam' => 'kara-age',
        'password' => bcrypt('100013933'),
        ],
        [
        'name' => 'Tomomi',
        'hometeam' => '9-A',
        'codingteam' => 'JIAOZI',
        'password' => bcrypt('100013922'),
        ],
        [
        'name' => 'Soy',
        'hometeam' => '9-A',
        'codingteam' => 'Kiwami Pudding',
        'password' => bcrypt('100013957'),
        ],
        [
        'name' => 'Jun1',
        'hometeam' => '9-A',
        'codingteam' => 'JIAOZI',
        'password' => bcrypt('100014042'),
        ],
        [
        'name' => 'Mihana',
        'hometeam' => '9-A',
        'codingteam' => 'Medium Rare',
        'password' => bcrypt('100013876'),
        ],
        [
        'name' => 'Tacky',
        'hometeam' => '9-A',
        'codingteam' => 'Pandanity',
        'password' => bcrypt('100013989'),
        ],
        [
        'name' => 'Hiro1',
        'hometeam' => '9-A',
        'codingteam' => 'Daichi+no+Megumi',
        'password' => bcrypt('100014054'),
        ],
        [
        'name' => 'Aki2',
        'hometeam' => '9-B',
        'codingteam' => 'Avengers',
        'password' => bcrypt('100013883'),
        ],
        [
        'name' => 'Dave',
        'hometeam' => '9-B',
        'codingteam' => 'kemkow',
        'password' => bcrypt('100013959'),
        ],
        [
        'name' => 'Yuka1',
        'hometeam' => '9-B',
        'codingteam' => 'JETS',
        'password' => bcrypt('100013970'),
        ],
        [
        'name' => 'Qoo',
        'hometeam' => '9-B',
        'codingteam' => 'Team One',
        'password' => bcrypt('100014115'),
        ],
        [
        'name' => 'Rin',
        'hometeam' => '9-B',
        'codingteam' => 'YAKITOMATO',
        'password' => bcrypt('100014047'),
        ],
        [
        'name' => 'Ryota',
        'hometeam' => '9-B',
        'codingteam' => 'なだ万',
        'password' => bcrypt('100014056'),
        ],
        [
        'name' => 'Lina',
        'hometeam' => '9-C',
        'codingteam' => 'HRM',
        'password' => bcrypt('100013943'),
        ],
        [
        'name' => 'Aki1',
        'hometeam' => '9-C',
        'codingteam' => 'HRM',
        'password' => bcrypt('100014061'),
        ],
        [
        'name' => 'Gon',
        'hometeam' => '9-C',
        'codingteam' => 'Team One',
        'password' => bcrypt('100014062'),
        ],
        [
        'name' => 'Meg',
        'hometeam' => '9-C',
        'codingteam' => '御富士も梅雨',
        'password' => bcrypt('100013904'),
        ],
        [
        'name' => 'Nana2',
        'hometeam' => '9-C',
        'codingteam' => 'HRM',
        'password' => bcrypt('100014078'),
        ],
        [
        'name' => 'Nao',
        'hometeam' => '9-C',
        'codingteam' => 'ひよこさん組',
        'password' => bcrypt('100014059'),
        ],
        [
        'name' => 'Yuu',
        'hometeam' => '10-A',
        'codingteam' => 'Pocket 6',
        'password' => bcrypt('100013974'),
        ],
        [
        'name' => 'Dsuke',
        'hometeam' => '10-A',
        'codingteam' => 'Eternal Dragon',
        'password' => bcrypt('100014072'),
        ],
        [
        'name' => 'Tsuxu',
        'hometeam' => '10-A',
        'codingteam' => 'Y. Nature',
        'password' => bcrypt('100013903'),
        ],
        [
        'name' => 'Shige',
        'hometeam' => '10-A',
        'codingteam' => 'なだ万',
        'password' => bcrypt('100014060'),
        ],
        [
        'name' => 'Kuni',
        'hometeam' => '10-A',
        'codingteam' => '卍Olive卍',
        'password' => bcrypt('100013976'),
        ],
        [
        'name' => 'Shuhei',
        'hometeam' => '10-A',
        'codingteam' => 'Ra Ra Ra RIZAP',
        'password' => bcrypt('100013965'),
        ],
        [
        'name' => 'Daiki2',
        'hometeam' => '10-B',
        'codingteam' => 'Koders',
        'password' => bcrypt('100014074'),
        ],
        [
        'name' => 'Mizuki2',
        'hometeam' => '10-B',
        'codingteam' => 'HRM',
        'password' => bcrypt('100013925'),
        ],
        [
        'name' => 'Naru',
        'hometeam' => '10-B',
        'codingteam' => 'Amigos',
        'password' => bcrypt('100013908'),
        ],
        [
        'name' => 'Tak3',
        'hometeam' => '10-B',
        'codingteam' => 'Eternal Dragon',
        'password' => bcrypt('100014003'),
        ],
        [
        'name' => 'Tera',
        'hometeam' => '10-B',
        'codingteam' => '卍Olive卍',
        'password' => bcrypt('100013977'),
        ],
        [
        'name' => 'Texas',
        'hometeam' => '10-B',
        'codingteam' => 'Team Sekaikan',
        'password' => bcrypt('100013975'),
        ],
        [
        'name' => 'Eco',
        'hometeam' => '10-C',
        'codingteam' => 'kemkow',
        'password' => bcrypt('100013893'),
        ],
        [
        'name' => 'Haru',
        'hometeam' => '10-C',
        'codingteam' => 'なだ万',
        'password' => bcrypt('100013905'),
        ],
        [
        'name' => 'Grace',
        'hometeam' => '10-C',
        'codingteam' => 'HRM',
        'password' => bcrypt('100013931'),
        ],
        [
        'name' => 'Kohei',
        'hometeam' => '10-C',
        'codingteam' => 'Pocket 6',
        'password' => bcrypt('100013964'),
        ],
        [
        'name' => 'Edward',
        'hometeam' => '10-C',
        'codingteam' => 'Eternal Dragon',
        'password' => bcrypt('100013911'),
        ],
        [
        'name' => 'Hiro2',
        'hometeam' => '10-C',
        'codingteam' => 'JIAOZI',
        'password' => bcrypt('100013982'),
        ],
        [
        'name' => 'Take',
        'hometeam' => '11-A',
        'codingteam' => '新鮮グミ',
        'password' => bcrypt('100014077'),
        ],
        [
        'name' => 'Kanako',
        'hometeam' => '11-A',
        'codingteam' => '御富士も梅雨',
        'password' => bcrypt('100013966'),
        ],
        [
        'name' => 'Yushi',
        'hometeam' => '11-A',
        'codingteam' => 'Jasmine',
        'password' => bcrypt('100014080'),
        ],
        [
        'name' => 'Fox',
        'hometeam' => '11-A',
        'codingteam' => 'YAKITOMATO',
        'password' => bcrypt('100013986'),
        ],
        [
        'name' => 'Maho',
        'hometeam' => '11-A',
        'codingteam' => 'Y. Nature',
        'password' => bcrypt('100013899'),
        ],
        [
        'name' => 'Mayuu',
        'hometeam' => '11-A',
        'codingteam' => 'Fortune',
        'password' => bcrypt('100013888'),
        ],
        [
        'name' => 'Reiko',
        'hometeam' => '11-B',
        'codingteam' => 'Porsche',
        'password' => bcrypt('100013916'),
        ],
        [
        'name' => 'Nakky',
        'hometeam' => '11-B',
        'codingteam' => 'Daichi+no+Megumi',
        'password' => bcrypt('100013901'),
        ],
        [
        'name' => 'Saeko',
        'hometeam' => '11-B',
        'codingteam' => 'Jasmine',
        'password' => bcrypt('100013892'),
        ],
        [
        'name' => 'Shu',
        'hometeam' => '11-B',
        'codingteam' => '卍Olive卍',
        'password' => bcrypt('100014081'),
        ],
        [
        'name' => 'Tyler',
        'hometeam' => '11-B',
        'codingteam' => 'Siésta',
        'password' => bcrypt('100013994'),
        ],
        [
        'name' => 'Emma',
        'hometeam' => '11-C',
        'codingteam' => 'Letian panda',
        'password' => bcrypt('100013896'),
        ],
        [
        'name' => 'Gino',
        'hometeam' => '11-C',
        'codingteam' => 'Porsche',
        'password' => bcrypt('100013927'),
        ],
        [
        'name' => 'Riku2',
        'hometeam' => '11-C',
        'codingteam' => 'youはたまご',
        'password' => bcrypt('100013997'),
        ],
        [
        'name' => 'Saki3',
        'hometeam' => '11-C',
        'codingteam' => 'Porsche',
        'password' => bcrypt('100014132'),
        ],
        [
        'name' => 'Tak1',
        'hometeam' => '11-C',
        'codingteam' => 'Team Sekaikan',
        'password' => bcrypt('100014087'),
        ],
        [
        'name' => 'Tatsuma',
        'hometeam' => '11-C',
        'codingteam' => 'kemkow',
        'password' => bcrypt('100014089'),
        ],
        [
        'name' => 'Annie',
        'hometeam' => '12-A',
        'codingteam' => 'Koders',
        'password' => bcrypt('100014025'),
        ],
        [
        'name' => 'Ellie',
        'hometeam' => '12-A',
        'codingteam' => 'youはたまご',
        'password' => bcrypt('100013919'),
        ],
        [
        'name' => 'Fumiya',
        'hometeam' => '12-A',
        'codingteam' => 'Kolkata (カルカッタ)',
        'password' => bcrypt('100014015'),
        ],
        [
        'name' => 'Ryoka',
        'hometeam' => '12-A',
        'codingteam' => 'Amigos',
        'password' => bcrypt('100014034'),
        ],
        [
        'name' => 'Ken',
        'hometeam' => '12-A',
        'codingteam' => 'Y. Nature',
        'password' => bcrypt('100014070'),
        ],
        [
        'name' => 'Tatsu',
        'hometeam' => '12-A',
        'codingteam' => 'YAKITOMATO',
        'password' => bcrypt('100014005'),
        ],
        [
        'name' => 'Dan',
        'hometeam' => '12-B',
        'codingteam' => 'Koders',
        'password' => bcrypt('100014094'),
        ],
        [
        'name' => 'Tomo2',
        'hometeam' => '12-B',
        'codingteam' => 'kara-age',
        'password' => bcrypt('100014100'),
        ],
        [
        'name' => 'Ash',
        'hometeam' => '12-B',
        'codingteam' => '卍Olive卍',
        'password' => bcrypt('100014091'),
        ],
        [
        'name' => 'Ricky',
        'hometeam' => '12-B',
        'codingteam' => 'Team One',
        'password' => bcrypt('100013890'),
        ],
        [
        'name' => 'Tiba',
        'hometeam' => '12-B',
        'codingteam' => 'YAKITOMATO',
        'password' => bcrypt('100013955'),
        ],
        [
        'name' => 'Yurino',
        'hometeam' => '12-B',
        'codingteam' => 'Fortune',
        'password' => bcrypt('100013971'),
        ],
        [
        'name' => 'Chloe',
        'hometeam' => '12-C',
        'codingteam' => 'TERAKOYA',
        'password' => bcrypt('100014126'),
        ],
        [
        'name' => 'Nate',
        'hometeam' => '12-C',
        'codingteam' => 'Fortune',
        'password' => bcrypt('100014009'),
        ],
        [
        'name' => 'Yuina',
        'hometeam' => '12-C',
        'codingteam' => 'Y. Nature',
        'password' => bcrypt('100014116'),
        ],
        [
        'name' => 'Erika',
        'hometeam' => '12-C',
        'codingteam' => 'Medium Rare',
        'password' => bcrypt('100014033'),
        ],
        [
        'name' => 'Marie1',
        'hometeam' => '12-C',
        'codingteam' => 'Ra Ra Ra RIZAP',
        'password' => bcrypt('100014082'),
        ],
        [
        'name' => 'Isshi',
        'hometeam' => '13-A',
        'codingteam' => 'Mkpali(ムカパリ)',
        'password' => bcrypt('100014055'),
        ],
        [
        'name' => 'Risako',
        'hometeam' => '13-A',
        'codingteam' => 'ぽなるけみり',
        'password' => bcrypt('100014057'),
        ],
        [
        'name' => 'Yuki2',
        'hometeam' => '13-A',
        'codingteam' => 'Medium Rare',
        'password' => bcrypt('100014010'),
        ],
        [
        'name' => 'Hondy',
        'hometeam' => '13-A',
        'codingteam' => 'Fortune',
        'password' => bcrypt('100014104'),
        ],
        [
        'name' => 'Ren',
        'hometeam' => '13-A',
        'codingteam' => 'Jasmine',
        'password' => bcrypt('100014106'),
        ],
        [
        'name' => 'Summer',
        'hometeam' => '13-A',
        'codingteam' => 'Pandanity',
        'password' => bcrypt('100013947'),
        ],
        [
        'name' => 'Saki2',
        'hometeam' => '13-A',
        'codingteam' => 'Eternal Dragon',
        'password' => bcrypt('100014050'),
        ],
        [
        'name' => 'Sally',
        'hometeam' => '13-A',
        'codingteam' => 'Mkpali(ムカパリ)',
        'password' => bcrypt('100014029'),
        ],
        [
        'name' => 'Yuji',
        'hometeam' => '13-A',
        'codingteam' => 'Avengers',
        'password' => bcrypt('100014105'),
        ],
        [
        'name' => 'Hannah',
        'hometeam' => '13-B',
        'codingteam' => 'Amigos',
        'password' => bcrypt('100014016'),
        ],
        [
        'name' => 'Daiki1',
        'hometeam' => '13-B',
        'codingteam' => 'いいとも',
        'password' => bcrypt('100014013'),
        ],
        [
        'name' => 'Marie2',
        'hometeam' => '13-B',
        'codingteam' => 'Pandanity',
        'password' => bcrypt('100013878'),
        ],
        [
        'name' => 'Nari',
        'hometeam' => '13-B',
        'codingteam' => 'BoB',
        'password' => bcrypt('100013921'),
        ],
        [
        'name' => 'Ruben',
        'hometeam' => '13-B',
        'codingteam' => 'BoB',
        'password' => bcrypt('100014107'),
        ],
        [
        'name' => 'Steph',
        'hometeam' => '13-B',
        'codingteam' => 'Eternal Dragon',
        'password' => bcrypt('100014073'),
        ],
        [
        'name' => 'Jack',
        'hometeam' => '13-C',
        'codingteam' => 'A BANANA',
        'password' => bcrypt('100014109'),
        ],
        [
        'name' => 'Mao',
        'hometeam' => '13-C',
        'codingteam' => 'いいとも',
        'password' => bcrypt('100014023'),
        ],
        [
        'name' => 'Ichiro',
        'hometeam' => '13-C',
        'codingteam' => 'Pandanity',
        'password' => bcrypt('100014090'),
        ],
        [
        'name' => 'Irisz',
        'hometeam' => '14-A',
        'codingteam' => 'A BANANA',
        'password' => bcrypt('100013962'),
        ],
        [
        'name' => 'Kana3',
        'hometeam' => '14-A',
        'codingteam' => 'Amigos',
        'password' => bcrypt('100013988'),
        ],
        [
        'name' => 'Kazumin',
        'hometeam' => '14-A',
        'codingteam' => 'TERAKOYA',
        'password' => bcrypt('100014014'),
        ],
        [
        'name' => 'Masaru',
        'hometeam' => '14-A',
        'codingteam' => 'Medium Rare',
        'password' => bcrypt('100014021'),
        ],
        [
        'name' => 'Yuka2',
        'hometeam' => '14-A',
        'codingteam' => 'Mkpali(ムカパリ)',
        'password' => bcrypt('100013885'),
        ],
        [
        'name' => 'Yuno',
        'hometeam' => '14-A',
        'codingteam' => '御富士も梅雨',
        'password' => bcrypt('100014111'),
        ],
        [
        'name' => 'Allie',
        'hometeam' => '14-B',
        'codingteam' => 'Fortune',
        'password' => bcrypt('100014075'),
        ],
        [
        'name' => 'Osa',
        'hometeam' => '14-B',
        'codingteam' => 'Letian panda',
        'password' => bcrypt('100014022'),
        ],
        [
        'name' => 'Taizan',
        'hometeam' => '14-B',
        'codingteam' => 'Avengers',
        'password' => bcrypt('100014112'),
        ],
        [
        'name' => 'Yuma',
        'hometeam' => '14-B',
        'codingteam' => 'SAKEty (酒ティー)',
        'password' => bcrypt('100014121'),
        ],
        [
        'name' => 'Miyu1',
        'hometeam' => '14-B',
        'codingteam' => 'Medium Rare',
        'password' => bcrypt('100013963'),
        ],
        [
        'name' => 'Megly',
        'hometeam' => '14-B',
        'codingteam' => 'kemkow',
        'password' => bcrypt('100013886'),
        ],
        [
        'name' => 'Yusuke',
        'hometeam' => '14-C',
        'codingteam' => 'kara-age',
        'password' => bcrypt('100014124'),
        ],
        [
        'name' => 'Kazane',
        'hometeam' => '14-C',
        'codingteam' => 'youはたまご',
        'password' => bcrypt('100014008'),
        ],
        [
        'name' => 'Michele',
        'hometeam' => '14-C',
        'codingteam' => 'Porsche',
        'password' => bcrypt('100013895'),
        ],
        [
        'name' => 'Shota',
        'hometeam' => '14-C',
        'codingteam' => 'kemkow',
        'password' => bcrypt('100014027'),
        ],
        [
        'name' => 'Natsu1',
        'hometeam' => '14-C',
        'codingteam' => 'Kiwami Pudding',
        'password' => bcrypt('119000254'),
        ],
        [
        'name' => 'Kaz',
        'hometeam' => '14-C',
        'codingteam' => 'Kiwami Pudding',
        'password' => bcrypt('100014125'),
        ],
        [
        'name' => 'Geeee',
        'hometeam' => '15-A',
        'codingteam' => 'A BANANA',
        'password' => bcrypt('100014028'),
        ],
        [
        'name' => 'Tak2',
        'hometeam' => '15-A',
        'codingteam' => 'CodeWars',
        'password' => bcrypt('100014096'),
        ],
        [
        'name' => 'Sarah',
        'hometeam' => '15-A',
        'codingteam' => 'TK Kingdom',
        'password' => bcrypt('100014053'),
        ],
        [
        'name' => 'Sophia',
        'hometeam' => '15-A',
        'codingteam' => 'Siésta',
        'password' => bcrypt('100013958'),
        ],
        [
        'name' => 'Kai',
        'hometeam' => '15-A',
        'codingteam' => 'Koders',
        'password' => bcrypt('100014118'),
        ],
        [
        'name' => 'Kana1',
        'hometeam' => '15-A',
        'codingteam' => 'youはたまご',
        'password' => bcrypt('100013891'),
        ],
        [
        'name' => 'Yuna',
        'hometeam' => '15-B',
        'codingteam' => 'Siésta',
        'password' => bcrypt('100014046'),
        ],
        [
        'name' => 'Miyu2',
        'hometeam' => '15-B',
        'codingteam' => 'Team Kay ',
        'password' => bcrypt('100013915'),
        ],
        [
        'name' => 'Mikako',
        'hometeam' => '15-B',
        'codingteam' => 'TK Kingdom',
        'password' => bcrypt('100013953'),
        ],
        [
        'name' => 'Fune',
        'hometeam' => '15-B',
        'codingteam' => 'Mkpali(ムカパリ)',
        'password' => bcrypt('100014051'),
        ],
        [
        'name' => 'Keisuke',
        'hometeam' => '15-B',
        'codingteam' => 'Noisyy',
        'password' => bcrypt('100014103'),
        ],
        [
        'name' => 'Yatty',
        'hometeam' => '15-C',
        'codingteam' => 'Noisyy',
        'password' => bcrypt('100014127'),
        ],
        [
        'name' => 'Tiny',
        'hometeam' => '15-C',
        'codingteam' => 'TERAKOYA',
        'password' => bcrypt('100014108'),
        ],
        [
        'name' => 'Otto',
        'hometeam' => '15-C',
        'codingteam' => 'The U.K',
        'password' => bcrypt('100014098'),
        ],
        [
        'name' => 'Reina',
        'hometeam' => '15-C',
        'codingteam' => 'Kiwami Pudding',
        'password' => bcrypt('100013887'),
        ],
        [
        'name' => 'Shiori',
        'hometeam' => '15-C',
        'codingteam' => 'CodeWars',
        'password' => bcrypt('100013998'),
        ],
        [
        'name' => 'Marcus',
        'hometeam' => '15-C',
        'codingteam' => 'youはたまご',
        'password' => bcrypt('100014058'),
        ],


      ]);
    }
}
